// Mocks generated by Mockito 5.3.2 from annotations
// in clean_arch_class/test/app/modules/home/domain/usecases/add_user_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_arch_class/app/modules/home/data/datasources/add_user_datasource.dart'
    as _i2;
import 'package:clean_arch_class/app/modules/home/domain/models/dtos/user_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddUserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddUserDataSource extends _i1.Mock implements _i2.AddUserDataSource {
  @override
  _i3.Future<Map<String, dynamic>> call(_i4.UserDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [dto],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
